package com.markettrender.newsemotions.service.impl;

public class MockStockNewsApiResponses {
	
	public static final String GET_DAILY_SENTIMENTS_RESPONSE = "{\n"
			+ "  \"total\": {\n"
			+ "    \"GOLD\": {\n"
			+ "      \"Total Positive\": 27,\n"
			+ "      \"Total Negative\": 3,\n"
			+ "      \"Total Neutral\": 15,\n"
			+ "      \"Sentiment Score\": 1.133\n"
			+ "    }\n"
			+ "  },\n"
			+ "  \"data\": {\n"
			+ "    \"2020-11-10\": {\n"
			+ "      \"GOLD\": {\n"
			+ "        \"Neutral\": 1,\n"
			+ "        \"Positive\": 1,\n"
			+ "        \"Negative\": 0,\n"
			+ "        \"sentiment_score\": 1.25\n"
			+ "      }\n"
			+ "    },\n"
			+ "    \"2020-11-06\": {\n"
			+ "      \"GOLD\": {\n"
			+ "        \"Neutral\": 0,\n"
			+ "        \"Positive\": 2,\n"
			+ "        \"Negative\": 0,\n"
			+ "        \"sentiment_score\": 1.5\n"
			+ "      }\n"
			+ "    }\n"
			+ "  },\n"
			+ "  \"total_pages\": 1\n"
			+ "}";
	
	public static final String GET_ALL_TICKERS_RESPONSE = "{\n"
			+ "  \"data\": [\n"
			+ "    {\n"
			+ "      \"ticker\": \"A\",\n"
			+ "      \"name\": \"Agilent Technologies, Inc.\",\n"
			+ "      \"country\": \"USA\",\n"
			+ "      \"industry\": \"Medical Laboratories & Research\",\n"
			+ "      \"sector\": \"Healthcare\",\n"
			+ "      \"has_news\": \"yes\",\n"
			+ "      \"ipo_date\": \"1999-11-18\",\n"
			+ "      \"exchange\": \"NYSE\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"ticker\": \"AA\",\n"
			+ "      \"name\": \"Alcoa Corporation\",\n"
			+ "      \"country\": \"USA\",\n"
			+ "      \"industry\": \"Aluminum\",\n"
			+ "      \"sector\": \"Basic Materials\",\n"
			+ "      \"has_news\": \"yes\",\n"
			+ "      \"ipo_date\": \"1962-01-02\",\n"
			+ "      \"exchange\": \"NYSE\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"ticker\": \"AABA\",\n"
			+ "      \"name\": \"Altaba Inc.\",\n"
			+ "      \"country\": \"USA\",\n"
			+ "      \"industry\": \"Asset Management\",\n"
			+ "      \"sector\": \"Financial\",\n"
			+ "      \"has_news\": \"yes\",\n"
			+ "      \"ipo_date\": \"1996-04-12\",\n"
			+ "      \"exchange\": null\n"
			+ "    }"
			+ "]"
			+ "}";

}
